services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/dotnet:1-7.0-bookworm
    volumes:
      - ../..:/workspaces:cached
      - ~/.aspnet/https:/home/vscode/.aspnet/https
    network_mode: service:mongo
    command: sleep infinity

  mongo:
    image: mongo:7.0.4

  mongo-express:
    image: mongo-express
    ports:
      - :8091
