name: build-dev

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write
    env:
      DOCKER_REGISTRY: ghcr.io
      DOCKER_IMAGE: ${{ github.repository }}
      DOCKERFILE_PATH: "src/AccessControlAPI"
    outputs:
      image_tags: ${{ steps.meta.outputs.tags }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up BuildKit Docker container builder to be able to build
      # multi-platform images and export cache
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
            version: v0.11.2

      # Login against a Docker DOCKER_REGISTRY except on PR
      # https://github.com/docker/login-action
      - name: Log into DOCKER_REGISTRY ${{ env.DOCKER_REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr

      # Build and push Docker image with Buildx
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.DOCKERFILE_PATH }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false

  openapi:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      # Extract OpenAPI Configuration File from the Docker image.
      # The file is generated in the Dockerfile and placed at the root.
      - name: Extract OpenAPI configuration file
        uses: shrink/actions-docker-extract@v3
        with:
          image: ${{ needs.docker.outputs.image_tags }}
          path: App/openapi.json
          destination: openapi.json

      # The OpenAPI Configuration File can generate multiple language packages.
      # This step store the artifact to be able to use it later.
      - name: Upload OpenAPI configuration file to artifact
        uses: actions/upload-artifact@v4.0.0
        with:
          name: openapi
          path: openapi.json
          
  openapi-typescript-angular:
    needs: openapi
    runs-on: ubuntu-latest
    env:
      PACKAGE_SCOPE: "$PACKAGE_SCOPE"
      PACKAGE_NAME: "$PACKAGE_NAME"
      PACKAGE_VERSION: "$PACKAGE_VERSION"
    steps:
      - run: |
          PACKAGE_SCOPE="@$(echo "${GITHUB_REPOSITORY%%/*}" | tr '[:upper:]' '[:lower:]')"
          PACKAGE_NAME="${GITHUB_REPOSITORY#*/}-client"
          echo "PACKAGE_SCOPE=$PACKAGE_SCOPE" >> $GITHUB_ENV
          echo "PACKAGE_NAME=$PACKAGE_NAME" >> $GITHUB_ENV
      - run: |
          BASE_VERSION="0.0.0"
          VERSION_SUFFIX=""

          if [ "${{ github.event_name }}" = "pull_request" ]; then
            VERSION_SUFFIX="-pr.${{ github.event.pull_request.number }}"
          else
            VERSION_SUFFIX=$(echo "${{ github.ref }}" | sed 's|refs/heads/||' | sed 's|/|-|g')
          fi

          echo "PACKAGE_VERSION=$BASE_VERSION$VERSION_SUFFIX" >> $GITHUB_ENV

      # Get a copy of the OpenAPI Configuration File in the local directory.
      - name: Download OpenAPI configuration file from artifact
        uses: actions/download-artifact@v4.1.0
        with:
          name: openapi
      
      # Generate a npm package for Angular library based on the OpenAPI Configuration File.
      - name: Generate Angular Client
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            openapitools/openapi-generator-cli \
              generate \
                -i /workspace/openapi.json \
                -g typescript-angular \
                -o /workspace/ \
                --additional-properties=npmName=$PACKAGE_SCOPE/$PACKAGE_NAME,npmVersion=$PACKAGE_VERSION

      # Setup the requirement for npm package
      - name: Set up Node.js
        uses: actions/setup-node@v4.0.1
        with:
          node-version: 18
          registry-url: 'https://npm.pkg.github.com'
          scope: '@utopiksandcastle'

      # Add information to the package configuration.
      - name: Configure package
        run: |
          jq '.repository = {"type": "git", "url": "git+https://github.com/${{ github.repository }}.git"}' package.json > tmp.json && mv tmp.json package.json
          jq '.author = "Utopik Sandcastle <utopiksandcastle@utopiksolutions.com>"' package.json > tmp.json && mv tmp.json package.json
      - run: cat package.json

      # Install requirement and build the package.
      - name: Build the package
        run: npm install
      - run: npm run build

      - name: Get the previous package id for the same version
        id: version_id
        uses: actions/github-script@v7
        with:
          script: |
            try {
              const response = await github.rest.packages.getAllPackageVersionsForPackageOwnedByOrg({
                org: context.repo.owner,
                package_name: process.env.PACKAGE_NAME,
              });
              const version = response.data.find(v => v.name === process.env.PACKAGE_VERSION);
              return version.id
            } catch (error) {
              console.error('An error occurred:', error.message);
              return 0
            }

      # Remove previous push of that version
      - name: Delete package
        if: steps.version_id.outputs.result != '0'
        uses: actions/delete-package-versions@v4
        with:
          package-name: $PACKAGE_NAME
          package-type: npm
          package-version-ids: ${{ steps.version_id.outputs.result }}

      # Publish the package.
      - name: Publish the package
        run: |
            npm publish --access public --tag dev
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
