name: Clean Up

on:
  pull_request:
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get PR number
        run: echo "PR number is ${{ github.event.pull_request.number }}"
