name: Clean Up

on:
  pull_request:
    branches: [ "main" ]
    # types: [closed]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  cleanup:
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    steps:
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Delete Docker Image
        env:
          TOKEN: ${{ github.token }}
          OWNER: ${{ github.repository_owner }}
          IMAGE: ${{ steps.meta.outputs.labels.org.opencontainers.image.title }}
          TAG: ${{ steps.meta.outputs.labels.org.opencontainers.image.version }}
        run: |
          echo "--"
          curl -L \
            -H "Authorization: token $TOKEN" \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/orgs/$OWNER/packages/container/$IMAGE/versions"
          echo "--"
