name: Clean Up

on:
  # schedule:
  #   - cron: '0 0 * * *'  # Run daily, modify as needed
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      # - name: Log into registry ${{ env.REGISTRY }}
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ${{ env.REGISTRY }}
      #     username: ${{ github.actor }}
      #     password: ${{ github.token }}

      - name: Delete Pull Request Docker Images
        env:
          TOKEN: ${{ github.token }}
          ORG: ${{ github.repository_owner }}
          PACKAGE_VERSION: pr-${{ github.event.pull_request.number }}
        run: |
          PACKAGE_NAME=${IMAGE_NAME#*/}

          # Fetch closed PRs
          closed_prs=$(curl -s \
                      -H "Authorization: token $TOKEN" \
                      -H "Accept: application/vnd.github+json" \
                      -H "X-GitHub-Api-Version: 2022-11-28" \
                      "https://api.github.com/repos/$ORG/$PACKAGE_NAME/pulls?state=closed" | jq -r '.[].number')

          # Convert open PRs to an array
          closed_prs_array=($closed_prs)

          # Fetch all tags for the GitHub Package
          tags_response=$(curl -s \
                      -H "Authorization: token $TOKEN" \
                      -H "Accept: application/vnd.github+json" \
                      -H "X-GitHub-Api-Version: 2022-11-28" \
                      "https://api.github.com/orgs/$ORG/packages/container/$PACKAGE_NAME/versions")

          # Loop over each tag
          echo "$tags_response" | jq -c '.[] | {id: .id, tags: .metadata.container.tags[]}' | while read -r tag_info; do
            tag=$(echo "$tag_info" | jq -r '.tags')
            version_id=$(echo "$tag_info" | jq -r '.id')

            # Check if tag starts with 'pr-' and is in closed PRs
            if [[ $tag == pr-* ]] && [[ " ${closed_prs_array[@]} " =~ " ${tag:3} " ]]; then
              echo "Deleting Docker image with tag $tag corresponding to closed PR #$tag"

              # Delete the Docker image version
              curl -s \
                  -H "Authorization: token $TOKEN" \
                  -H "Accept: application/vnd.github+json" \
                  -H "X-GitHub-Api-Version: 2022-11-28" \
                   "https://api.github.com/orgs/$ORG/packages/container/$PACKAGE_NAME/versions/$version_id"
            fi
          done
