name: Clean Up

on:
  schedule:
    - cron: '0 0 * * 0'  # Run at 00:00 on Sunday.
  pull_request:
    # types: [closed]
    branches: [ "main" ] #TODO: Debug: Remove

jobs:
  delete-package-versions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Delete Versions of All Packages for Closed PRs
        uses: actions/github-script@v7
        with:
          script: |
            const org = context.repo.owner;
            const repo = context.repo.repo;

            // Fetch closed PRs
            const closedPrsResponse = await github.rest.pulls.list({
              owner: org,
              repo: repo,
              state: 'closed'
            });
            const closedPrNumbers = closedPrsResponse.data.map(pr => pr.number);

            // Fetch all packages owned by the organization
            const packagesResponse = await github.rest.packages.getAllPackageVersionsForPackageOwnedByOrg({
              org: org,
              package_type: 'container' // Adjust the package type as needed
            });

            // Iterate over each package
            for (const package of packagesResponse.data) {
              // Fetch all versions for each package
              const versionsResponse = await github.rest.packages.getAllPackageVersionsForPackageOwnedByOrg({
                org: org,
                package_type: 'container', // Adjust the package type as needed
                package_name: package.name
              });

              // Iterate over each version
              for (const version of versionsResponse.data) {
                // Check if version corresponds to a closed PR
                if (closedPrNumbers.includes(parseInt(version.name))) {
                  // Delete the package version
                  await github.rest.packages.deletePackageVersionForOrg({
                    org: org,
                    package_type: 'container', // Adjust the package type as needed
                    package_name: package.name,
                    package_version_id: version.id,
                  });
                  console.log(`Deleted package version: ${version.id} corresponding to PR #${version.name}`);
                }
              }
            }
            
