name: Clean Up

on:
  pull_request:
    branches: [ "main" ]
    # types: [closed]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  cleanup:
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    steps:
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Delete Docker Image
        env:
          TOKEN: ${{ github.token }}
          OWNER: ${{ github.repository_owner }}
          TAG: 'pr-${{ github.event.pull_request.number }}'
        run: |
          VERSION_ID=$(curl -H "Authorization: token $TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/orgs/$OWNER/packages/container/$IMAGE_NAME/versions" | jq '.[] | select(.metadata.container.tags[]=="'$TAG'").id')
          echo $VERSION_ID
