name: Clean Up

on:
  pull_request:
    types: [closed]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_NAME: pr-${{ github.event.pull_request.number }}

jobs:
  cleanup:
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    steps:
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Delete Docker Image
        env:
          TOKEN: ${{ github.token }}
          ORG: ${{ github.repository_owner }}
          PACKAGE_NAME: ${IMAGE_NAME%%/*}
          PACKAGE_VERSION: ${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}
        run: |
          PACKAGE_VERSION_ID=$(curl -L \
            -H "Authorization: token $TOKEN" \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/orgs/$ORG/packages/container/$PACKAGE_NAME/versions" | jq '.[] | select(.metadata.container.tags[]=="'$PACKAGE_VERSION'").id')
                    
          curl -X DELETE \
            -H "Authorization: token $TOKEN" \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/orgs/$ORG/packages/container/$PACKAGE_NAME/versions/$PACKAGE_VERSION_ID"

          echo "Deleting image ${{ steps.meta.outputs.tags }} with version Id $PACKAGE_VERSION_ID"
